# This script provides plotting functions to visualize correlation of the fitted and outcome values.

# Plotting for regression -----

#' Plot fitted values versus outcome for regression predx objects.
#'
#' @description Generates a point plot with for the fitted and outcome values for
#' regression predictions with a fitted trend as an option.
#' @details The fitted trend is generated by \code{\link[ggplot2]{geom_smooth}}.
#' @param predx_object an object of class 'predx_object' created e.g. by \code{\link{predict.caretx}}.
#' @param x_var name of the variable presented in the X axis.
#' @param y_var name of the variable presented in the Y axis.
#' @param point_size size of the plot points.
#' @param point_shape shape of the points.
#' @param point_wjitter horizontal jittering of the points.
#' @param point_hjitter vertical jittering of the points.
#' @param point_alpha plot point alpha.
#' @param show_trend logical, should a trend line be displayed?
#' @param trend_method a method for fitting the trend line, see \code{\link[ggplot2]{geom_smooth}} for details, defaults to 'lm'.
#' @param show_calibration logical, should a line with slope 1 and intercept 1 be displayed in the plot?
#' @param line_size size of the calibration or trend line.
#' @param plot_title plot title.
#' @param plot_subtitle plot subtitle.
#' @param plot_tag plot tag, number of complete observations if not specified by the user.
#' @param x_lab X axis title.
#' @param y_lab Y axis title.
#' @param cust_theme customized plot theme provided by the user.
#' @param ... extra arguments passed to \code{\link[ggplot2]{geom_smooth}}.
#' @return returns a  ggplot object.

  plot_regression <- function(predx_object,
                              x_var = '.outcome',
                              y_var = '.fitted',
                              point_size = 2,
                              point_shape = 21,
                              point_color = 'steelblue',
                              point_wjitter = 0.01,
                              point_hjitter = 0.01,
                              point_alpha = 0.75,
                              show_trend = TRUE,
                              trend_method = 'lm',
                              show_calibration = TRUE,
                              line_size = 0.5,
                              plot_title = NULL,
                              plot_subtitle = NULL,
                              plot_tag = NULL,
                              x_lab = x_var,
                              y_lab = y_var,
                              cust_theme = ggplot2::theme_classic(), ...) {

    ## entry control

    stopifnot(class(predx_object) == 'predx')
    stopifnot(is.logical(show_trend))
    stopifnot(is.logical(show_calibration))
    stopifnot(any(class(cust_theme) == 'theme'))
    stopifnot(is.numeric(line_size))

    if(predx_object$type %in% c('multi_class', 'binary')) {

      warning('Regression plots for the multi-class or binary predictions are not available.', call. = FALSE)

      return(NULL)

    }

    if(is.null(plot_tag)) {

      plot_tag <- paste('n =', nrow(predx_object$data))

    }

    ## plotting

    reg_plot <- ggplot2::ggplot(predx_object$data,
                                ggplot2::aes(x = .data[[x_var]],
                                             y = .data[[y_var]])) +
      ggplot2::geom_point(shape = point_shape,
                          size = point_size,
                          alpha = point_alpha,
                          fill = point_color,
                          position = ggplot2::position_jitter(width = point_wjitter, height = point_hjitter)) +
      cust_theme +
      ggplot2::labs(title = plot_title,
                    subtitle = plot_subtitle,
                    tag = plot_tag,
                    x = x_lab,
                    y = y_lab)

    if(show_trend) {

      reg_plot <- reg_plot +
        ggplot2::geom_smooth(method = trend_method,
                             size = line_size, ...)

    }

    if(show_calibration) {

      reg_plot <- reg_plot +
        ggplot2::geom_abline(intercept = 0,
                             slope = 1,
                             color = 'black',
                             size = line_size)

    }

    reg_plot

  }

# Binary classification: ROC plot ------

#' Plot a receiver-operator characteristic curve (ROC) for a binary classification predx object.
#'
#' @description Generates a ROC plot with for the fitted and outcome values.
#' Optionally, a custom annotation inside the plot may be added.
#' @details The plot is generated by \code{\link[plotROC]{geom_roc}}.
#' @param predx_object an object of class 'predx_object' created e.g. by \code{\link{predict.caretx}}.
#' @param line_color color of the ROC line.
#' @param line_size size of the ROC line.
#' @param cutoffs_at numeric, between 0 and 1, indicates the cutpoints to be presented in the ROC curve.
#' @param point_size size of the cutoff point.
#' @param plot_title plot title.
#' @param plot_subtitle plot subtitle.
#' @param plot_tag plot tag, contains the number of complate observations and events if not specified by the user.
#' @param annotation_txt annotation text.
#' @param annotation_color annotation text color.
#' @param annotation_size size of the annotation text and of the cutoff label.
#' @param annotation_x annotation x position.
#' @param annotation_y annotation y position.
#' @param annotation_hjust horizontal justification of the annotation text.
#' @param annotation_vjust horizontal justification of the annotation text.
#' @param cust_theme customized plot theme provided by the user.
#' @param ... extra arguments passed to \code{\link[plotROC]{geom_roc}}.
#' @return returns a  ggplot object.

  plot_roc <- function(predx_object,
                       line_color = 'steelblue',
                       line_size = 0.5,
                       cutoffs_at = 0.5,
                       point_size = 0.3,
                       plot_title = NULL,
                       plot_subtitle = NULL,
                       plot_tag = NULL,
                       annotation_txt = NULL,
                       annotation_color = line_color,
                       annotation_size = 2.75,
                       annotation_x = 0.6,
                       annotation_y = 0.3,
                       annotation_hjust = 0,
                       annotation_vjust = 1,
                       cust_theme = NULL, ...) {

    ## entry control

    stopifnot(class(predx_object) == 'predx')

    if(!is.null(cust_theme)) stopifnot(any(class(cust_theme) == 'theme'))

    if(predx_object$type %in% c('regression', 'multi_class')) {

      warning('ROC plots for the multi-class or regression  predictions are not available.', call. = FALSE)

      return(NULL)

    }

    if(is.null(plot_tag)) {

      plot_tag <- paste0('total: n = ', nrow(predx_object$data),
                         ', events: n = ', dplyr::count(predx_object$data, .outcome)[2, 2])

    }

    if(is.factor(predx_object$data[['.outcome']])) {

      data <- dplyr::mutate(predx_object$data,
                            .outcome = as.numeric(.outcome) - 1)

    } else {

      data <- predx_object$data

    }

    if(is.null(plot_tag)) {

      plot_tag <- paste0('total: n = ', nrow(predx_object$data),
                         ', events: n = ', dplyr::count(predx_object$data, .outcome)[2, 2])

    }

    ## plotting

    roc_plot <- ggplot2::ggplot(data,
                                ggplot2::aes(d = .data[['.outcome']],
                                             m = .data[[predx_object$classes[2]]])) +
      plotROC::geom_roc(labelsize = annotation_size,
                        cutoffs.at = cutoffs_at,
                        pointsize = point_size,
                        color = line_color,
                        size = line_size, ...) +
      plotROC::style_roc() +
      ggplot2::geom_abline(slope = 1,
                           intercept = 0,
                           linetype = 'dashed') +
      ggplot2::labs(title = plot_title,
                    subtitle = plot_subtitle,
                    tag = plot_tag)

    if(!is.null(cust_theme)) {

      roc_plot <- roc_plot +
        cust_theme

    }

    if(!is.null(annotation_txt)) {

      roc_plot +
        ggplot2::annotate('text',
                          label = annotation_txt,
                          x = annotation_x,
                          y = annotation_y,
                          hjust = annotation_hjust,
                          vjust = annotation_vjust,
                          size = annotation_size)

    } else {

      roc_plot

    }

  }

# Classification models: plots of confusion matrix -----

#' Plot confusion matrix for a classification predx object.
#'
#' @description Generates a heat map representation of the confusion matrix.
#' Outcome is presented in the X axis, fitted is presented in the Y axis.
#' @param predx_object an object of class 'predx_object' created e.g. by \code{\link{predict.caretx}}.
#' @param scale indicates, how the table is to be scales. 'none' returns the counts, 'fraction' returns the fraction
#' of all observations, 'percent' returns the percent of all observations. Defaults to 'none'.
#' @param show_labels logical, indicates if counts/fractions/percents are shown in the plot.
#' @param label_size size of the label text.
#' @param label_color color of the label text.
#' @param signif_digits significant digits for rounding of the label values.
#' @param plot_title plot title.
#' @param plot_subtitle plot subtitle.
#' @param plot_tag plot tag, contains a reference to scale and the observation number if not specified.
#'
#' @param cust_theme customized plot theme provided by the user.
#' @return returns a ggplot object.

  plot_confusion <- function(predx_object,
                             scale = c('none', 'fraction', 'percent'),
                             show_labels = TRUE,
                             label_size = 2.75,
                             label_color = 'black',
                             signif_digits = 2,
                             plot_title = NULL,
                             plot_subtitle = NULL,
                             plot_tag = NULL,
                             x_lab = '.outcome',
                             y_lab = '.fitted',
                             cust_theme = ggplot2::theme_classic()) {

    ## entry control

    stopifnot(class(predx_object) == 'predx')
    stopifnot(any(class(cust_theme) == 'theme'))
    stopifnot(is.logical(show_labels))

    if(!is.null(cust_theme)) stopifnot(any(class(cust_theme) == 'theme'))

    if(predx_object$type == 'regression') {

      warning('Confusion matrix in not available for regression predictions.', call. = FALSE)

      return(NULL)

    }

    if(is.null(plot_tag)) {

      scale_lab <- c('none' = 'Counts',
                     'fraction' = 'Fraction of total',
                     'percent' = '% of total')

      plot_tag <- paste0(scale_lab[scale],
                         ', total: n = ', nrow(predx_object$data))

    }

    ## plotting

    conf <- as.data.frame(confusion(predx_object, scale = scale))

    conf_plot <- ggplot2::ggplot(conf,
                                 ggplot2::aes(x = .data[['.outcome']],
                                              y = .data[['.fitted']],
                                              fill = .data[['Freq']])) +
      ggplot2::geom_tile(color = 'black') +
      ggplot2::scale_fill_gradient2(low = 'steelblue',
                                    high = 'firebrick',
                                    mid = 'white') +
      cust_theme +
      ggplot2::labs(title = plot_title,
                    subtitle = plot_subtitle,
                    tag = plot_tag,
                    x = x_lab,
                    y = y_lab,
                    fill = NULL)

    if(show_labels) {

      conf_plot +
        ggplot2::geom_text(ggplot2::aes(label = signif(.data[['Freq']], signif_digits)),
                           size = label_size,
                           hjust = 0.5,
                           vjust = 0.5,
                           color = label_color)

    } else {

      conf_plot

    }

  }



